os:
  - linux

before_install:
  - sudo apt-get install git-svn

language: csharp
mono: none
dotnet: 3.1.0
script:
 - chmod +x build.sh
 - chmod +x test.sh
 - chmod +x package.sh
 - ./build.sh
 - ./test.sh
 - ./package.sh

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  file:
   - "svn2gitnet-ubuntu-x64.tar.gz"
   - "svn2gitnet-centos-x64.tar.gz"
   - "svn2gitnet-debian-x64.tar.gz"
   - "svn2gitnet-fedora-x64.tar.gz"
   - "svn2gitnet-rhel-x64.tar.gz"
   - "svn2gitnet-osx-x64.tar.gz"
  skip_cleanup: true
  on:
    tags: true